# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a069628e5cad10227e3c403eece388940c67b22585d1cf7bbb2207dddbaaac6853c3045cf216d83b376e76738b3e7e1244b0b28cc5a879276bffbd67475de2a

test:
  secret_key_base: b3e953973fc2b2b43223088f8f4a039e189c08cdd9e24f8c6cfc9f3acbbcc533f5b6adb8d5aeb98a5b1e67e86e7eb78900178a295cebed235738e744360281ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
